### PR TITLE
New license - Apache 2.0

### PR DESCRIPTION
**Pull request by topisani**
any objections? @IntricateEngineers/devs

### CODE REVIEW

**Comment by VelocityRa** [comment]
[Looks good to me](https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29)

**Comment by Drullkus** [comment]
👍 

I would like textures to be licensed to CC-0.

**Comment by topisani** [comment]
good idea @Drullkus ill make that happen!

**Comment by Lanse505** [comment]
I'm fine with this licence change

**Comment by srs-bsns** [comment]
in the LICENCE file, you can remove all the boilerplate stuff at the bottom. Everything below `END OF TERMS AND CONDITIONS`.
Just sayin'.

**Comment by VelocityRa** [comment]
Done. @topisani Isn't it time we merged this? You're still not sold on this licence?

**Comment by topisani** [comment]
mainly i dontr really care for this one and wanna write some simple one myself, and also, i really cant be bothered to resolve the conflicts. im also not a fan of having to keep some copyright notice on top of all the files

**Comment by VelocityRa** [comment]
Yeah merging is gonna get a bit ugly and there's not really a need. Lets just delete the branch, if you're ok with that.
About the licence, wouldn't it be easier to put one that represents what we want best instead of "writing our own", which we don't really know all that much about that stuff; I sure don't.
I don't think we have to add a notice to _every_ file, do we?

**Comment by topisani** [comment]
yeah idk, i dont really care a lot about the license, i just want it to be permissive without trapping us in some shit - thats why i think going no license and just a little ruleset by us on what you can do and what you cant would be better

**Comment by VelocityRa** [comment]
Alright, let's close this for now and we'll discuss this.

**Pull request closed without merging**
